### ISSUE TITLE
I can't make It work

### ISSUE THREAD

**Issue by mvindel-dev** [robingenz/ionic-capacitor-barcode-scanner#3]
Hey, i've followed the steps in the guide to install and try to read a qr but It doesn't work for me, when I click the scan button It asks me the grant permisions for the camara but doesn't do anything else.
I have a public repository where the error can be found, the code is in src/view/team anda the repository is https://github.com/mvindel-dev/PokeAPI @robingenz

**Comment by robingenz** [comment]
I close this as duplicate of https://github.com/capawesome-team/capacitor-mlkit/discussions/143
